import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const STORAGE_KEY="cashflow101:realtime-config",PLAYER_KEY="cashflow101:player-id";
const state={supabase:null,channel:null,roomCode:null,playerId:localStorage.getItem(PLAYER_KEY)||crypto.randomUUID(),playerName:localStorage.getItem("cashflow101:player-name")||"",ready:false,players:[],gameState:{phase:"lobby",version:0,hostId:null}};
localStorage.setItem(PLAYER_KEY,state.playerId);
const $=id=>document.getElementById(id);
const els={setupCard:$("setupCard"),lobbyCard:$("lobbyCard"),setupError:$("setupError"),supabaseUrl:$("supabaseUrl"),supabaseKey:$("supabaseKey"),connectBtn:$("connectBtn"),connectionBadge:$("connectionBadge"),playerName:$("playerName"),saveNameBtn:$("saveNameBtn"),createRoomBtn:$("createRoomBtn"),joinRoomBtn:$("joinRoomBtn"),roomCodeInput:$("roomCodeInput"),activeRoom:$("activeRoom"),roomCodeLabel:$("roomCodeLabel"),copyRoomBtn:$("copyRoomBtn"),leaveRoomBtn:$("leaveRoomBtn"),playerCount:$("playerCount"),hostLabel:$("hostLabel"),phaseLabel:$("phaseLabel"),readyBtn:$("readyBtn"),playersList:$("playersList")};
els.playerName.value=state.playerName;
const normalizeCode=v=>(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);
const makeRoomCode=()=>{const c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>c[Math.floor(Math.random()*c.length)]).join("")};
function setConnection(online,label=online?"Online":"Offline"){els.connectionBadge.textContent=label;els.connectionBadge.className="badge "+(online?"online":"offline")}
function showError(m){els.setupError.textContent=m||""}
function getConfig(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||"null")}catch{return null}}
function saveName(){state.playerName=els.playerName.value.trim().slice(0,24)||"Player";els.playerName.value=state.playerName;localStorage.setItem("cashflow101:player-name",state.playerName);if(state.channel)trackPresence()}
function currentHost(){return[...state.players].sort((a,b)=>a.joinedAt-b.joinedAt)[0]||null}
function renderPlayers(){const host=currentHost();state.gameState.hostId=host?.id||null;els.playerCount.textContent=String(state.players.length);els.hostLabel.textContent=host?host.name:"Waiting...";els.phaseLabel.textContent=state.gameState.phase||"Lobby";els.readyBtn.textContent=state.ready?"Not Ready":"Ready";els.readyBtn.className=state.ready?"secondary":"primary";els.playersList.innerHTML="";for(const p of[...state.players].sort((a,b)=>a.joinedAt-b.joinedAt)){const row=document.createElement("div");row.className="player";const name=document.createElement("strong");name.className="player-name";name.textContent=p.name+(p.id===state.playerId?" (You)":"");const meta=document.createElement("div");meta.className="player-meta";if(p.id===host?.id){const t=document.createElement("span");t.className="tag host";t.textContent="HOST";meta.appendChild(t)}const r=document.createElement("span");r.className="tag"+(p.ready?" ready":"");r.textContent=p.ready?"READY":"WAITING";meta.appendChild(r);row.append(name,meta);els.playersList.appendChild(row)}}
function readPresence(){if(!state.channel)return;const ps=state.channel.presenceState(),players=[];for(const[key,metas]of Object.entries(ps)){const m=metas?.[metas.length-1];if(m)players.push({id:key,name:m.name||"Player",ready:Boolean(m.ready),joinedAt:Number(m.joinedAt)||Date.now()})}state.players=players;renderPlayers()}
async function trackPresence(){if(!state.channel)return;const s=await state.channel.track({id:state.playerId,name:state.playerName||"Player",ready:state.ready,joinedAt:state.joinedAt});if(s!=="ok")throw new Error("Could not publish player presence.")}
async function broadcastGameState(){if(!state.channel)return;const host=currentHost();if(!host||host.id!==state.playerId)return;state.gameState={...state.gameState,hostId:host.id,players:state.players.map(({id,name,ready})=>({id,name,ready})),version:Date.now()};await state.channel.send({type:"broadcast",event:"game_state",payload:state.gameState})}
async function joinRoom(code){code=normalizeCode(code);if(code.length!==6){showError("Enter a valid 6-character room code.");return}if(!state.playerName)state.playerName="Player";if(state.channel)await leaveRoom();state.roomCode=code;state.ready=false;state.joinedAt=Date.now();state.channel=state.supabase.channel("cashflow101:"+code,{config:{presence:{key:state.playerId},broadcast:{self:true}}});state.channel.on("presence",{event:"sync"},async()=>{readPresence();await broadcastGameState()}).on("presence",{event:"join"},async()=>{readPresence();await broadcastGameState()}).on("presence",{event:"leave"},async()=>{readPresence();await broadcastGameState()}).on("broadcast",{event:"game_state"},({payload})=>{if(!payload||Number(payload.version)<Number(state.gameState.version||0))return;state.gameState=payload;renderPlayers()});state.channel.subscribe(async status=>{if(status==="SUBSCRIBED"){setConnection(true,"Connected");await trackPresence();showRoom()}else if(status==="CHANNEL_ERROR"||status==="TIMED_OUT"){setConnection(false);showError("Realtime connection failed. Check your Supabase settings.")}});history.replaceState(null,"","?room="+code)}
async function leaveRoom(){if(state.channel){try{await state.channel.untrack()}catch{}await state.supabase.removeChannel(state.channel)}state.channel=null;state.roomCode=null;state.players=[];state.ready=false;els.activeRoom.classList.add("hidden");history.replaceState(null,"",location.pathname);renderPlayers()}
function showRoom(){els.activeRoom.classList.remove("hidden");els.roomCodeLabel.textContent=state.roomCode;renderPlayers()}
async function connect(){const url=els.supabaseUrl.value.trim(),key=els.supabaseKey.value.trim();if(!url||!key){showError("Supabase URL and publishable/anon key are required.");return}try{new URL(url);state.supabase=createClient(url,key);localStorage.setItem(STORAGE_KEY,JSON.stringify({url,key}));setConnection(false,"Connecting...");showError("");els.setupCard.classList.add("hidden");els.lobbyCard.classList.remove("hidden");const room=normalizeCode(new URLSearchParams(location.search).get("room")||"");if(room)await joinRoom(room)}catch(e){console.error(e);setConnection(false);showError("Could not connect. Check the Supabase URL and key.")}}
els.connectBtn.addEventListener("click",connect);els.saveNameBtn.addEventListener("click",saveName);els.createRoomBtn.addEventListener("click",()=>joinRoom(makeRoomCode()));els.joinRoomBtn.addEventListener("click",()=>joinRoom(els.roomCodeInput.value));els.roomCodeInput.addEventListener("input",()=>els.roomCodeInput.value=normalizeCode(els.roomCodeInput.value));els.readyBtn.addEventListener("click",async()=>{state.ready=!state.ready;await trackPresence();readPresence();await broadcastGameState()});els.leaveRoomBtn.addEventListener("click",leaveRoom);els.copyRoomBtn.addEventListener("click",async()=>{if(!state.roomCode)return;const u=new URL(location.href);u.searchParams.set("room",state.roomCode);await navigator.clipboard.writeText(u.toString());els.copyRoomBtn.textContent="Copied";setTimeout(()=>els.copyRoomBtn.textContent="Copy Code",1200)});
const saved=getConfig();if(saved?.url&&saved?.key){els.supabaseUrl.value=saved.url;els.supabaseKey.value=saved.key;connect()}
